version: 0.2

phases:
  install:
    commands:
        - npm install
  pre-build:
    commands:
        - npm run lint
        - npm run test
  build:
    commands:
        - npm run build
     
artifacts:
  files:
    - sma/**/*