version: 0.2

phases:
  install:
    commands:
        - npm install
  pre_build:
    commands:
        - pwd
        - ls -a
        - npm run lint
        - npm run test
  build:
    commands:
        - npm run build
     
artifacts:
  files:
    - sma/**/*
